"""
Django settings for zian_tsabit_be project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_flag(name, default='0'):
    """Read a boolean from the environment, treating '0'/'false'/'' as off."""
    return os.environ.get(name, default) not in ('0', 'false', 'False', '')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# The three settings below read the environment, because docker-compose.yml has
# always passed DEBUG and DJANGO_ALLOWED_HOSTS and nothing here looked at them.
# The defaults keep a bare `manage.py runserver` working as before.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-zs8oieo0yf+afuwc-@typ_rbq_4*2@tbwf9aoz18-q3s=ne43w',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_flag('DEBUG', '1')

# Space-separated, matching the form the compose file already used.
ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost 127.0.0.1 [::1]'
).split()

# The SPA is always on a different origin than this API -- Vite on :5173 in
# development, nginx on :8080 in Docker -- so every browser fetch is cross-origin
# and dies at preflight without these. Defaults cover both local setups; set the
# variable to the real site origin when deploying.
# 5173 is `npm run dev`, 4173 is `npm run preview`, 8080 is the nginx container.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173 http://127.0.0.1:5173 '
    'http://localhost:4173 http://127.0.0.1:4173 '
    'http://localhost:8080 http://127.0.0.1:8080',
).split()

# The SPA's admin page logs in with a session cookie, so the browser has to be
# allowed to attach credentials to a cross-origin request. Without this the
# cookie is silently dropped and every write is 403 despite a successful login.
CORS_ALLOW_CREDENTIALS = True

# Django compares the Origin of an unsafe cross-origin request against this list
# before it even looks at the CSRF token. It defaults to the CORS origins,
# because the SPA allowed to read the API is the one that has to write to it.
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS', ' '.join(CORS_ALLOWED_ORIGINS)
).split()

# 'Lax' is enough as long as the SPA and the API share a registrable domain --
# both on localhost in development, ziantsabit.com and api.ziantsabit.com in
# production; a port does not make two origins cross-*site*. A deployment where
# they genuinely differ needs 'None', which browsers only honour on a Secure
# cookie, so change all four of these together in that case.
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SECURE = _env_flag('SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = _env_flag('CSRF_COOKIE_SECURE')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'myapp',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Session auth covers the browsable API while logged into /admin/; basic auth
    # makes `curl -u user:pass` work for writes from a terminal.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'ziantsabit.com API',
    'DESCRIPTION': (
        'Content API for ziantsabit.com. Posts are filed under one category — '
        'books, projects or garage_sale — and addressed by slug.'
    ),
    'VERSION': '1.0.0',
    # The schema endpoint is served separately; listing it inside its own output
    # is noise.
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Has to sit above CommonMiddleware: preflight OPTIONS requests need a
    # response before anything else gets a chance to redirect or reject them.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zian_tsabit_be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zian_tsabit_be.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
