"""
Django settings for ziantsabit_be project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_flag(name, default='0'):
    """Read a boolean from the environment, treating '0'/'false'/'' as off."""
    return os.environ.get(name, default) not in ('0', 'false', 'False', '')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# The three settings below read the environment, because docker-compose.yml has
# always passed DEBUG and DJANGO_ALLOWED_HOSTS and nothing here looked at them.
# The defaults keep a bare `manage.py runserver` working as before.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-zs8oieo0yf+afuwc-@typ_rbq_4*2@tbwf9aoz18-q3s=ne43w',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_flag('DEBUG', '1')

# Space-separated, matching the form the compose file already used.
ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost 127.0.0.1 [::1]'
).split()

# The SPA is always on a different origin than this API -- Vite on :5173 in
# development, nginx on :8080 in Docker -- so every browser fetch is cross-origin
# and dies at preflight without these. Defaults cover both local setups; set the
# variable to the real site origin when deploying.
# 5173 is `npm run dev`, 4173 is `npm run preview`, 8080 is the nginx container.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173 http://127.0.0.1:5173 '
    'http://localhost:4173 http://127.0.0.1:4173 '
    'http://localhost:8080 http://127.0.0.1:8080',
).split()

# The SPA's admin page logs in with a session cookie, so the browser has to be
# allowed to attach credentials to a cross-origin request. Without this the
# cookie is silently dropped and every write is 403 despite a successful login.
CORS_ALLOW_CREDENTIALS = True

# Django compares the Origin of an unsafe cross-origin request against this list
# before it even looks at the CSRF token. It defaults to the CORS origins,
# because the SPA allowed to read the API is the one that has to write to it.
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS', ' '.join(CORS_ALLOWED_ORIGINS)
).split()

# 'Lax' is enough as long as the SPA and the API share a registrable domain --
# both on localhost in development, ziantsabit.com and api.ziantsabit.com in
# production; a port does not make two origins cross-*site*. A deployment where
# they genuinely differ needs 'None', which browsers only honour on a Secure
# cookie, so change all four of these together in that case.
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SECURE = _env_flag('SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = _env_flag('CSRF_COOKIE_SECURE')

# Behind cloudflared (or any TLS-terminating proxy) Django receives plain HTTP
# and would otherwise report every request as insecure. Off by default and
# switched on only by the deployment, because trusting a header the client can
# also send is only safe when nothing can reach this process directly -- which
# is true behind the tunnel and false for a local `runserver` on :8000.
if _env_flag('USE_X_FORWARDED_PROTO'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # Required by Post.tags, which is an ArrayField. Django refuses the system
    # check without it (postgres.E005) rather than failing at query time.
    'django.contrib.postgres',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'myapp',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Session auth covers the browsable API while logged into /admin/; basic auth
    # makes `curl -u user:pass` work for writes from a terminal.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'ziantsabit.com API',
    'DESCRIPTION': (
        'Content API for ziantsabit.com. Posts are filed under one category — '
        'books, projects or garage_sale — and addressed by slug.'
    ),
    'VERSION': '1.0.0',
    # The schema endpoint is served separately; listing it inside its own output
    # is noise.
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Directly below SecurityMiddleware and above everything else, as WhiteNoise
    # documents: a static file should be answered without running sessions,
    # auth or CSRF over it.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Has to sit above CommonMiddleware: preflight OPTIONS requests need a
    # response before anything else gets a chance to redirect or reject them.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ziantsabit_be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ziantsabit_be.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Postgres only -- there is no sqlite fallback, so every environment (bare
# `manage.py runserver` included) needs a reachable Postgres server. Defaults
# match the `db` service docker-compose.yml starts alongside `api`; anything
# outside Docker needs at least POSTGRES_HOST (and POSTGRES_PASSWORD, if the
# server does not use the same throwaway dev credentials) set for real.
# Connection options, only for a Postgres that is not the `db` service beside
# this one. Over the compose network there is nothing between the two containers
# to encrypt against; a database on another host is a different matter.
#
# libpq's default sslmode is 'prefer', which negotiates TLS when the server
# offers it and **silently falls back to plaintext when it does not** -- so it
# is not a setting that can fail, and therefore not one that protects anything.
# 'require' is the meaningful floor. It encrypts but does not authenticate the
# server; 'verify-full' does both and needs POSTGRES_SSLROOTCERT pointing at the
# CA that signed the server's certificate (mount it into the container).
_db_options = {}
if os.environ.get('POSTGRES_SSLMODE'):
    _db_options['sslmode'] = os.environ['POSTGRES_SSLMODE']
if os.environ.get('POSTGRES_SSLROOTCERT'):
    _db_options['sslrootcert'] = os.environ['POSTGRES_SSLROOTCERT']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'zian_tsabit_be'),
        'USER': os.environ.get('POSTGRES_USER', 'zian_tsabit_be'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        # Left empty unless asked for, so the local and Docker setups connect
        # exactly as they always have.
        'OPTIONS': _db_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Where `collectstatic` gathers Django admin's, DRF's and drf-spectacular's own
# assets for WhiteNoise to serve. Deliberately *outside* /app: docker-compose.yml
# bind-mounts the source tree over /app for autoreload, which would shadow a
# collected directory built into the image (and drop a build artefact into the
# working copy on the host).
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles')


# Uploaded images
# ---------------
# Post images live in an S3-compatible bucket -- RustFS in development, via the
# `rustfs` service in docker-compose.yml -- rather than on the API container's
# disk, which is ephemeral and would lose every upload on a rebuild. Nothing
# below names the server: this is django-storages' generic S3 backend, which is
# why replacing MinIO with RustFS was a compose change and not a code change.
#
# Two endpoints, and they are genuinely different addresses:
#
#   AWS_S3_ENDPOINT_URL         Django -> RustFS. Inside Docker this is
#                               http://rustfs:9000, a name only the compose
#                               network resolves.
#   AWS_S3_PUBLIC_ENDPOINT_URL  browser -> RustFS. Has to be an address the
#                               visitor's machine can reach, so it cannot be
#                               the internal one.
#
# Getting this wrong is the classic object-storage-behind-Docker bug: uploads
# succeed, and every <img> points at a host the browser has never heard of.
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'ziantsabit-media')
AWS_S3_ACCESS_KEY_ID = os.environ.get('AWS_S3_ACCESS_KEY_ID', 'rustfsadmin')
AWS_S3_SECRET_ACCESS_KEY = os.environ.get('AWS_S3_SECRET_ACCESS_KEY', 'rustfsadmin')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'http://localhost:9000')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')

# A self-hosted bucket is served as a path (host/bucket/key), not as a
# subdomain, unless you own wildcard DNS for it. boto3 defaults to virtual-host
# style and would address a bucket nobody can resolve.
AWS_S3_ADDRESSING_STYLE = 'path'

# The bucket is public-read (docker-compose.yml's `storage-init` puts that
# policy on it), so object URLs need no signature. Signed URLs expire, which
# would rot every image on a page a visitor -- or a CDN -- had cached.
AWS_QUERYSTRING_AUTH = False

# Per-object ACLs are unsupported by RustFS by design (and were only partly
# implemented by MinIO); the bucket policy is what makes objects readable, so
# don't send an ACL at all.
AWS_DEFAULT_ACL = None

# Never clobber an existing key. The upload view already appends a random
# suffix, so this is the second half of the same guarantee.
AWS_S3_FILE_OVERWRITE = False

_public_endpoint = os.environ.get(
    'AWS_S3_PUBLIC_ENDPOINT_URL', AWS_S3_ENDPOINT_URL
).rstrip('/')
_public_scheme, _, _public_host = _public_endpoint.rpartition('://')
# django-storages builds a URL as `{AWS_S3_URL_PROTOCOL}//{AWS_S3_CUSTOM_DOMAIN}/{key}`,
# and with path-style addressing the bucket is part of that host-and-path prefix.
AWS_S3_URL_PROTOCOL = f'{_public_scheme or "http"}:'
AWS_S3_CUSTOM_DOMAIN = f'{_public_host}/{AWS_STORAGE_BUCKET_NAME}'

STORAGES = {
    'default': {'BACKEND': 'storages.backends.s3.S3Storage'},
    # Compressed: WhiteNoise pre-builds .gz/.br beside each file at collect time
    # and serves those. Manifest: filenames get a content hash, which is what
    # makes the immutable far-future caching it applies to them safe.
    #
    # Manifest storage only when DEBUG is off, because it cannot resolve a
    # {% static %} tag at all until `collectstatic` has run -- and a bare
    # `manage.py runserver` or `manage.py test` outside Docker never runs it.
    # In the container entrypoint.sh does, before anything serves a request.
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Largest image the upload endpoint accepts, in bytes. Django spools anything
# over FILE_UPLOAD_MAX_MEMORY_SIZE to a temp file, so this is a policy limit
# rather than a memory guard.
MAX_UPLOAD_SIZE = int(os.environ.get('MAX_UPLOAD_SIZE', 10 * 1024 * 1024))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
