# Generated by Django 5.2.16 on 2026-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("books", "Books"),
                            ("projects", "Projects"),
                            ("garage_sale", "Garage Sale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("excerpt", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="myapp_post_categor_f3c795_idx",
                    )
                ],
            },
        ),
    ]
