# Generated by Django 6.1 on 2026-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('books', 'Books'), ('projects', 'Projects'), ('garage_sale', 'Garage Sale')], max_length=20),
        ),
    ]
