# Generated by Django 6.1 on 2026-08-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_days', to='myapp.post')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='myapp_postv_date_796716_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'date'), name='unique_post_view_day')],
            },
        ),
    ]
