version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin        # change for production
      POSTGRES_PASSWORD: admin    # change for production
      POSTGRES_DB: mydatabase     # initial database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: